# fly.toml app configuration file for warehouse-rl-api
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'warehouse-rl-api'
primary_region = 'ewr'

[build]
  dockerfile = "Web_App/Dockerfile"

[http_service]
  internal_port = 8080
  protocol = "tcp"
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 1
  processes = ['app']

  [[http_service.ports]]
    port = 80
  [[http_service.ports]]
    port = 443

  [[http_service.checks]]
    type = "http"
    path = "/api/health"
    interval = "5s"
    timeout = "2s"
    grace_period = "25s"
    method = "GET"
    port = 8080

  [http_service.concurrency]
    type = "requests"
    hard_limit = 25
    soft_limit = 20

[[vm]]
  memory = '4gb'
  cpu_kind = 'performance'
  cpus = 2
