# fly.toml app configuration file generated for web-app-solitary-bush-6980 on 2025-08-09T15:34:46-04:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

#app = 'rl-navigation'
app = 'warehouse-rl'
primary_region = 'ewr'

[build]

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 1
  processes = ['app']

[[checks]]
  name     = "http_check"
  type     = "http"
  port     = 3000
  interval = "10s"
  timeout  = "2s"
  method   = "get"
  path     = "/"


[build.args]
  NEXT_PUBLIC_API_URL = "https://api.rl-navigation.com"
  NEXT_PUBLIC_WS_URL  = "wss://api.rl-navigation.com"


[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
