# fly.toml app configuration file generated for web-app-solitary-bush-6980 on 2025-08-09T15:34:46-04:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'warehouse-rl'
primary_region = 'ewr'

[build]

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = false
  auto_start_machines = true
  min_machines_running = 1
  processes = ['app']

[build.args]
  NEXT_PUBLIC_API_URL = "https://warehouse-rl-api.fly.dev"
  NEXT_PUBLIC_WS_URL  = "wss://warehouse-rl-api.fly.dev"


[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
